# Generated by Django 4.0.2 on 2022-02-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('descripcion_proyecto', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_admin', to='planner.colaborador')),
                ('colaboradores', models.ManyToManyField(blank=True, null=True, related_name='proyecto_colab', to='planner.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('codigo_tarea', models.CharField(max_length=30, unique=True)),
                ('descripcion_tarea', models.TextField()),
                ('prioridad_tarea', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.IntegerField(null=True)),
                ('estado_tarea', models.CharField(max_length=30)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.proyecto')),
                ('usuarios_asignados', models.ManyToManyField(blank=True, null=True, to='planner.Colaborador')),
            ],
        ),
    ]
